spring.application.name=assessment-service
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.config.import=optional:configserver:http://config-server:8888
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mysupersecretkeymysupersecretkey123456

services.auth-service.url=http://auth-service:8080
services.user-service.url=http://user-service:8081
services.course-service.url=http://course-service:8082
services.enrollment-service.url=http://enrollment-service:8084
services.certificate-service.url=http://certificate-service:8085

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted