spring.application.name=course-service
server.port=8082
spring.datasource.url=jdbc:mysql://mysql:3306/lms?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.config.import=optional:configserver:http://config-server:8888
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mysupersecretkeymysupersecretkey123456

services.auth-service.url=http://auth-service:8080
services.user-service.url=http://user-service:8081
services.assessment-service.url=http://assessment-service:8083
services.enrollment-service.url=http://enrollment-service:8084
services.certificate-service.url=http://certificate-service:8085

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted