spring.application.name=api-gateway
server.port=9000
spring.config.import=optional:configserver:http://config-server:8888
# Auth Service  →  http://auth-service:8080
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=http://auth-service:8080
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

# User Service  →  http://user-service:8081
spring.cloud.gateway.mvc.routes[1].id=user-service
spring.cloud.gateway.mvc.routes[1].uri=http://user-service:8081
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/admin/**, /api/internal/users/**

# Course Service  →  http://course-service:8082
spring.cloud.gateway.mvc.routes[2].id=course-service
spring.cloud.gateway.mvc.routes[2].uri=http://course-service:8082
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/courses/**, /api/lessons/**, /api/categories/**

# Assessment Service  →  http://assessment-service:8083
spring.cloud.gateway.mvc.routes[3].id=assessment-service
spring.cloud.gateway.mvc.routes[3].uri=http://assessment-service:8083
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/quizzes/**, /api/quizzes-exams/**, /api/questions/**

# Enrollment Service  →  http://enrollment-service:8084
spring.cloud.gateway.mvc.routes[4].id=enrollment-service
spring.cloud.gateway.mvc.routes[4].uri=http://enrollment-service:8084
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/enrollments/**

# Certificate Service  →  http://certificate-service:8085
spring.cloud.gateway.mvc.routes[5].id=certificate-service
spring.cloud.gateway.mvc.routes[5].uri=http://certificate-service:8085
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/certificates/**
logging.level.org.springframework.cloud.gateway=INFO


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted